name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0 # Fetch all history for all tags and branches

    - name: Check Formatting with Clang-Format
      run: |
          # Find C++ source and header files in relevant directories, ignore errors for non-existent paths
          $files = Get-ChildItem -Recurse -Include *.cpp, *.h, *.hpp -Path src, include, tests, cli/toolsrc -ErrorAction SilentlyContinue # Add other source directories if needed
          if ($files) {
            # Ensure clang-format is available (usually is on windows-latest)
            # Run check: --dry-run shows changes without applying, -Werror treats warnings (like formatting mismatches) as errors
            clang-format --dry-run --Werror $files.FullName
            Write-Host "Clang-Format check passed."
          } else {
            Write-Host "No C++ files found to format check."
          }
      shell: pwsh # Use PowerShell

    - name: Bootstrap vcpkg
      run: cli/bootstrap-vcpkg.bat -disableMetrics
      shell: cmd # Use cmd for .bat script

    - name: Configure CMake
      run: |
        cmake -B build -S . "-DCMAKE_TOOLCHAIN_FILE=cli/scripts/buildsystems/vcpkg.cmake"
      shell: pwsh # Use PowerShell for CMake commands

    - name: Build Project
      run: cmake --build build --config Release
      shell: pwsh # Use PowerShell for CMake commands