name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Bootstrap vcpkg
      run: cli/bootstrap-vcpkg.bat -disableMetrics
      shell: cmd # Use cmd for .bat script

    - name: Configure CMake
      run: |
        cmake -B build -S . "-DCMAKE_TOOLCHAIN_FILE=cli/scripts/buildsystems/vcpkg.cmake"
      shell: pwsh # Use PowerShell for CMake commands

    - name: Build Project
      run: cmake --build build --config Release
      shell: pwsh # Use PowerShell for CMake commands